// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDStxN0PlGdKzl1dHTl0k_jP-c5RRHv2Oo',
    appId: '1:832686445701:web:f42d44ec72040d8c0685ec',
    messagingSenderId: '832686445701',
    projectId: 'pink-2fa57',
    authDomain: 'pink-2fa57.firebaseapp.com',
    storageBucket: 'pink-2fa57.firebasestorage.app',
    measurementId: 'G-ZL0Y1J5T4G',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyANjs-rhKXBK25ibJnsW2KjnNdddhKOzTc',
    appId: '1:832686445701:android:01002161e85c495a0685ec',
    messagingSenderId: '832686445701',
    projectId: 'pink-2fa57',
    storageBucket: 'pink-2fa57.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAhjd6Xe_vUS68_DFN-A1L755IOucA_oGU',
    appId: '1:832686445701:ios:d1e95ac74a820c160685ec',
    messagingSenderId: '832686445701',
    projectId: 'pink-2fa57',
    storageBucket: 'pink-2fa57.firebasestorage.app',
    iosBundleId: 'com.example.pink',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAhjd6Xe_vUS68_DFN-A1L755IOucA_oGU',
    appId: '1:832686445701:ios:d1e95ac74a820c160685ec',
    messagingSenderId: '832686445701',
    projectId: 'pink-2fa57',
    storageBucket: 'pink-2fa57.firebasestorage.app',
    iosBundleId: 'com.example.pink',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDStxN0PlGdKzl1dHTl0k_jP-c5RRHv2Oo',
    appId: '1:832686445701:web:c4dbe4199f1b7e3d0685ec',
    messagingSenderId: '832686445701',
    projectId: 'pink-2fa57',
    authDomain: 'pink-2fa57.firebaseapp.com',
    storageBucket: 'pink-2fa57.firebasestorage.app',
    measurementId: 'G-QMDPS700B5',
  );
}
